[network]
host = "127.0.0.1"
port = 6969
public_host = "http://127.0.0.1:6969"
allow_private_network = false

[db]
host = "127.0.0.1"
port = 6961

[peers]
bootstrap_peers = ["http://shoggoth.network:6969"]

[explorer]
enable = true

[api]
enable = true
rate_limiter_requests = 1000
rate_limiter_duration = 10000 # milliseconds

[storage]
max_resource_size = 50 # Gigabytes
limit = 100 # Gigabytes

[dht]
enable_updater = true
updater_frequency = 5 # seconds

[update]
enable = true
id = "SHOG590ea3b939a7fe15b342ff74fb192a7e"
